### ISSUE TITLE
PowerType not usable under ArchLinux with PowerShell 7.2.6

### ISSUE THREAD

**Issue by KJP12** [AnderssonPeter/PowerType#37]
**Describe the bug**
When trying to enable PowerType to use it, it emits an unsupported platform error:
`Enable-PowerType: Operation is not supported on this platform.`

**To Reproduce**
1. `Install-Module PowerType -AllowPrerelease`
2. `Enable-PowerType`

**Expected behavior**
To function as expected from the README.

**Environment (please complete the following information):**
 - OS: ArchLinux running Linux 5.19.11-arch1-1
 - PowerShell version: 7.2.6
 - PSReadLine version: 2.2.6
 - PowerType version: 0.0.13

$PSVersionTable
```ps1
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Linux 5.19.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 24 Sep 2022 18:24:15 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**
Using <https://stackoverflow.com/a/798136> to get the error.

Inspecting the source, it faults around here: https://github.com/AnderssonPeter/PowerType/blob/d1c6cc1c3e66ea75216669b5dc1778502d4ce2b7/PowerType/BackgroundProcessing/ExecutionEngineThread.cs#L93-L99

<details><summary>The underlying error & stack trace</summary>

```ps1
PSMessageDetails      : 
Exception             : System.PlatformNotSupportedException: Operation is not supported on this platform.
                           at System.Management.Automation.Internal.SecuritySupport.SetExecutionPolicy(ExecutionPolicyScope scope, ExecutionPolicy policy, String shellId)
                           at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean 
                        local, Boolean setLocation)
                           at System.Management.Automation.AutomationEngine..ctor(PSHost hostInterface, InitialSessionState iss)
                           at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
                           at System.Management.Automation.Runspaces.LocalRunspace.OpenHelper(Boolean syncCall)
                           at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall)
                           at System.Management.Automation.Runspaces.RunspaceBase.Open()
                           at PowerType.BackgroundProcessing.ExecutionEngineThread.CreateRunspace() in 
                        D:\a\PowerType\PowerType\PowerType\BackgroundProcessing\ExecutionEngineThread.cs:line 99
                           at PowerType.BackgroundProcessing.ExecutionEngineThread..ctor(ThreadQueue`1 queue) in 
                        D:\a\PowerType\PowerType\PowerType\BackgroundProcessing\ExecutionEngineThread.cs:line 29
                           at PowerType.BackgroundProcessing.ExecutionEngine.Start() in D:\a\PowerType\PowerType\PowerType\BackgroundProcessing\ExecutionEngine.cs:line 29
                           at PowerType.PowerTypePredictor..ctor(ICurrentWorkingDirectoryProvider currentWorkingDirectoryProvider, IEnumerable`1 dictionaryFiles) in 
                        D:\a\PowerType\PowerType\PowerType\PowerTypePredictor.cs:line 28
                           at PowerType.EnablePowerTypePredictor.ProcessRecord() in D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 56
                           at System.Management.Automation.Cmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Enable-PowerType], PlatformNotSupportedException
FullyQualifiedErrorId : System.PlatformNotSupportedException,PowerType.EnablePowerTypePredictor
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}



MyCommand             : Enable-PowerType
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 1
OffsetInLine          : 1
HistoryId             : 50
ScriptName            : 
Line                  : Enable-PowerType
PositionMessage       : At line:1 char:1
                        + Enable-PowerType
                        + ~~~~~~~~~~~~~~~~
PSScriptRoot          : 
PSCommandPath         : 
InvocationName        : Enable-PowerType
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition : 


00000000000000000000000000000000000000000000000000000000000000000000000000000000

TargetSite     : Void SetExecutionPolicy(Microsoft.PowerShell.ExecutionPolicyScope, Microsoft.PowerShell.ExecutionPolicy, System.String)
Message        : Operation is not supported on this platform.
Data           : {}
InnerException : 
HelpLink       : 
Source         : System.Management.Automation
HResult        : -2146233031
StackTrace     :    at System.Management.Automation.Internal.SecuritySupport.SetExecutionPolicy(ExecutionPolicyScope scope, ExecutionPolicy policy, String shellId)
                    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, 
                 Boolean setLocation)
                    at System.Management.Automation.AutomationEngine..ctor(PSHost hostInterface, InitialSessionState iss)
                    at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
                    at System.Management.Automation.Runspaces.LocalRunspace.OpenHelper(Boolean syncCall)
                    at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall)
                    at System.Management.Automation.Runspaces.RunspaceBase.Open()
                    at PowerType.BackgroundProcessing.ExecutionEngineThread.CreateRunspace() in D:\a\PowerType\PowerType\PowerType\BackgroundProcessing\ExecutionEngineThread.cs:line 99
                    at PowerType.BackgroundProcessing.ExecutionEngineThread..ctor(ThreadQueue`1 queue) in 
                 D:\a\PowerType\PowerType\PowerType\BackgroundProcessing\ExecutionEngineThread.cs:line 29
                    at PowerType.BackgroundProcessing.ExecutionEngine.Start() in D:\a\PowerType\PowerType\PowerType\BackgroundProcessing\ExecutionEngine.cs:line 29
                    at PowerType.PowerTypePredictor..ctor(ICurrentWorkingDirectoryProvider currentWorkingDirectoryProvider, IEnumerable`1 dictionaryFiles) in 
                 D:\a\PowerType\PowerType\PowerType\PowerTypePredictor.cs:line 28
                    at PowerType.EnablePowerTypePredictor.ProcessRecord() in D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 56
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
```
</details>

**Comment by AnderssonPeter** [comment]
Thanks for the issue looks like it doesn't allow `ExecutionPolicy.Unrestricted`, to be honest I haven't tried this on linux yet so it might not be Arch specific.

**Comment by AnderssonPeter** [comment]
@KJP12 could you try 0.0.15 and see if that works as expected?

**Comment by KJP12** [comment]
`Enable-PowerType` now throws a URI parsing exception. It seems like either .NET Core or PowerShell doesn't return the location information, given the following:

```ps1
> [System.Reflection.Assembly]::GetExecutingAssembly()

GAC    Version        Location
---    -------        --------
False  v4.0.30319     

```

Location however might be just blank here because it is being interpreted. Although, it's possible that it is getting *something* for a URI anyways, given that `/home/name` and `@` both being passed into the URI builder return the same error without giving *any* useful information, which seems like a rather odd choice of .NET for being able to debug it, since it removes any ability to even know why. It does seem that `C:/home/name` does however get correctly converted to the file protocol with it returning `file:///C:/home/name`. It might be more ideal to go ahead and process the path through a URL escaper then prepending `file:///` before it before throwing it at URI? That would also account for `#` and `?` being present, even if it isn't normally allowed by Windows.

<details><summary>Example from <code>[System.UriBuilder]::new("@")</code></summary>

```ps1
PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" 
                        argument(s): "Invalid URI: The hostname could not be parsed."
                         ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
                           at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& 
                        creationOptions)
                           at System.Uri..ctor(String uriString)
                           at System.UriBuilder..ctor(String uri)
                           at CallSite.Target(Closure , CallSite , Type , String )
                           --- End of inner exception stack trace ---
                           at 
                        System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception 
                        exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Type , String )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : UriFormatException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}



MyCommand             : 
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 1
OffsetInLine          : 1
HistoryId             : -1
ScriptName            : 
Line                  : [System.UriBuilder]::new("@")
PositionMessage       : At line:1 char:1
                        + [System.UriBuilder]::new("@")
                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : 
PSCommandPath         : 
InvocationName        : 
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition : 


00000000000000000000000000000000000000000000000000000000000000000000000000000000

ErrorRecord                 : Exception calling ".ctor" with "1" argument(s): "Invalid URI: The hostname could not be 
                              parsed."
WasThrownFromThrowStatement : False
TargetSite                  : Void ConvertToMethodInvocationException(System.Exception, System.Type, System.String, Int32, 
                              System.Reflection.MemberInfo)
Message                     : Exception calling ".ctor" with "1" argument(s): "Invalid URI: The hostname could not be 
                              parsed."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.UriFormatException: Invalid URI: The hostname could not be parsed.
                                 at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, 
                              UriCreationOptions& creationOptions)
                                 at System.Uri..ctor(String uriString)
                                 at System.UriBuilder..ctor(String uri)
                                 at CallSite.Target(Closure , CallSite , Type , String )
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exc
                              eption exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                                 at CallSite.Target(Closure , CallSite , Type , String )
                                 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 
                              arg1)
                                 at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame 
                              frame)
                                 at 
                              System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                              frame)


11111111111111111111111111111111111111111111111111111111111111111111111111111111

TargetSite     : Void CreateThis(System.String, Boolean, System.UriKind, System.UriCreationOptions ByRef)
Message        : Invalid URI: The hostname could not be parsed.
Data           : {}
InnerException : 
HelpLink       : 
Source         : System.Private.Uri
HResult        : -2146233033
StackTrace     :    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& 
                 creationOptions)
                    at System.Uri..ctor(String uriString)
                    at System.UriBuilder..ctor(String uri)
                    at CallSite.Target(Closure , CallSite , Type , String )

```

</details>

Relevant code:
https://github.com/AnderssonPeter/PowerType/blob/96ad1426d7aa2e340003f5eb16545ea9870b19d7/PowerType/EnablePowerTypePredictor.cs#L66-L74

---

<details><summary>New error with URI</summary>

```ps1
PSMessageDetails      : 
Exception             : System.UriFormatException: Invalid URI: The hostname could not be parsed.
                           at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& 
                        creationOptions)
                           at System.Uri..ctor(String uriString)
                           at System.UriBuilder..ctor(String uri)
                           at PowerType.EnablePowerTypePredictor.get_AssemblyPath() in 
                        D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 70
                           at PowerType.EnablePowerTypePredictor.get_ModuleDirectory() in 
                        D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 76
                           at PowerType.EnablePowerTypePredictor.get_DictionariesDirectory() in 
                        D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 78
                           at PowerType.EnablePowerTypePredictor.GetDictionaries()+MoveNext() in 
                        D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 82
                           at PowerType.PowerTypePredictor..ctor(ICurrentWorkingDirectoryProvider 
                        currentWorkingDirectoryProvider, IEnumerable`1 dictionaryFiles) in 
                        D:\a\PowerType\PowerType\PowerType\PowerTypePredictor.cs:line 30
                           at PowerType.EnablePowerTypePredictor.ProcessRecord() in 
                        D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 56
                           at System.Management.Automation.Cmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Enable-PowerType], UriFormatException
FullyQualifiedErrorId : System.UriFormatException,PowerType.EnablePowerTypePredictor
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}



MyCommand             : Enable-PowerType
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 1
OffsetInLine          : 1
HistoryId             : 4
ScriptName            : 
Line                  : Enable-PowerType
PositionMessage       : At line:1 char:1
                        + Enable-PowerType
                        + ~~~~~~~~~~~~~~~~
PSScriptRoot          : 
PSCommandPath         : 
InvocationName        : Enable-PowerType
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition : 


00000000000000000000000000000000000000000000000000000000000000000000000000000000

TargetSite     : Void CreateThis(System.String, Boolean, System.UriKind, System.UriCreationOptions ByRef)
Message        : Invalid URI: The hostname could not be parsed.
Data           : {}
InnerException : 
HelpLink       : 
Source         : System.Private.Uri
HResult        : -2146233033
StackTrace     :    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& 
                 creationOptions)
                    at System.Uri..ctor(String uriString)
                    at System.UriBuilder..ctor(String uri)
                    at PowerType.EnablePowerTypePredictor.get_AssemblyPath() in 
                 D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 70
                    at PowerType.EnablePowerTypePredictor.get_ModuleDirectory() in 
                 D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 76
                    at PowerType.EnablePowerTypePredictor.get_DictionariesDirectory() in 
                 D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 78
                    at PowerType.EnablePowerTypePredictor.GetDictionaries()+MoveNext() in 
                 D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 82
                    at PowerType.PowerTypePredictor..ctor(ICurrentWorkingDirectoryProvider currentWorkingDirectoryProvider, 
                 IEnumerable`1 dictionaryFiles) in D:\a\PowerType\PowerType\PowerType\PowerTypePredictor.cs:line 30
                    at PowerType.EnablePowerTypePredictor.ProcessRecord() in 
                 D:\a\PowerType\PowerType\PowerType\EnablePowerTypePredictor.cs:line 56
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
```

</details>

**Comment by AnderssonPeter** [comment]
Sorry for the huge delay, if you have the time, could you create a unit test that recreates the issue and create a fix and send them as a PR?

**Comment by fluentmoheshwar** [comment]
I get this error in Ubuntu
```
Enable-PowerType: Invalid URI: The hostname could not be parsed.
```

**Comment by AnderssonPeter** [comment]
Guessing the issue is on all Linux based systems.
I don't currently have a linux install with powershell.
If you can provide a unit test that recreates the issue then I might be able to fix it!

**Comment by fluentmoheshwar** [comment]
> Guessing the issue is on all Linux based systems.
> I don't currently have a linux install with powershell.
> If you can provide a unit test that recreates the issue then I might be able to fix it!

Well, I don't have experience in C# so I don't think I can do it :)

**Comment by AnderssonPeter** [comment]
@fluentmoheshwar @Ampflower Could you guys try `0.0.16` and see if that solves the issue?

**Comment by fluentmoheshwar** [comment]
![image](https://github.com/AnderssonPeter/PowerType/assets/65463913/cac68715-8bfa-48f9-8ad4-b2a2edff6e53)
It works!

**Comment by AnderssonPeter** [comment]
Great :) sorry that it took so much time to fix the issue.
